<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="" method="post">
        <label for="mail">
            <input type="email" name="mail">
            E-Mail
        </label>
        <label for="pass">
            <input type="password" name="pass">
            Password
        </label>
        <button type="submit">login</button>
    </form>
</body>
</html>